name: 'TRMNL'
description: 'TRMNL Server'
version: '1.0.0'
slug: 'trmnl'
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  2443/tcp: 2443
  2300/tcp: 2300
